name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
          - os: ubuntu-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Install Linux dependencies
      run: |
        pip install meson

    - name: Execute build
      env:
        CC: ${{ matrix.cc }}
      run: |
        meson setup build
        meson compile -C build

  windows:
    name: Build ${{ matrix.target.name }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          {"name": "Windows 10",   "args": "-Dc_args='-D_WIN32_WINNT=0x0A00'"},
          {"name": "Windows XP",   "args": "-Dc_args='-D_WIN32_WINNT=0x0502'"},
          {"name": "UWP",          "args": "-Dc_args='-DWINAPI_FAMILY=WINAPI_FAMILY_APP'"},
        ]
    runs-on: windows-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v7

    - name: Install Windows dependencies
      run: pip install meson

    - name: Execute build
      run: |
        meson setup ${{ matrix.target.args }} build
        meson compile -C build

  macos:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v7

    - name: Install macOS dependencies
      run: pip install meson

    - name: Execute build
      run: |
        meson setup build
        meson compile -C build
