name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
          - os: ubuntu-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Install Linux dependencies
      run: |
        pip install meson

    - name: Execute build
      env:
        CC: ${{ matrix.cc }}
      run: |
        meson setup build
        meson compile -C build
