name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
          - os: ubuntu-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7

    - name: Install Linux dependencies
      run: |
        pip install meson

    - name: Execute build
      env:
        CC: ${{ matrix.cc }}
      run: |
        meson setup build
        meson compile -C build

  windows:
    strategy:
      fail-fast: false
      matrix:
        winver: ['0x0A00', '0x502']
    runs-on: windows-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v7

    - name: Install Windows dependencies
      run: pip install meson

    - name: Execute build
      run: |
        meson setup -Dc_args="-D_WIN32_WINNT=${{matrix.winver}}" build
        meson compile -C build

  macos:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v7

    - name: Install macOS dependencies
      run: pip install meson

    - name: Execute build
      run: |
        meson setup build
        meson compile -C build
