name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: Install Linux dependencies
        run: |
          pip install meson

      - name: Generate build database
        run: |
          meson setup build

      - uses: cpp-linter/cpp-linter-action@v2.20.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''  # No clang-format
          version: 22 # clang-tidy 22
          tidy-checks: '' # Use .clang-tidy config file
          thread-comments: ${{ github.event_name != 'pull_request' && 'update' }}
          step-summary: ${{ github.event_name == 'pull_request' && 'update' }}
          files-changed-only: false # always run the analysis
          database: "build" # path to meson compile_commands.json file
          ignore: subprojects|build
